executable = /home/yxiu/Code/NeuralUDF/bashs/bash_garment_test_ft.sh
arguments = --gpu 0 --case $(MyArg1)

error = /home/yxiu/Code/NeuralUDF/logs/test_wmask_$(MyArg1).err
output = /home/yxiu/Code/NeuralUDF/logs/test_wmask_$(MyArg1).out
log = /home/yxiu/Code/NeuralUDF/logs/test_wmask_$(MyArg1).log

request_memory = 50000
request_disk = 5G
request_cpus = 6
request_gpus = 1
requirements = TARGET.CUDACapability > 7.5
requirements = TARGET.CUDAGlobalMemoryMb > 10000

queue MyArg1 from /home/yxiu/Code/NeuralUDF/tmp_lst.txt
