executable = /home/yxiu/Code/NeuralUDF/bashs/bash_garment_blending.sh
arguments = --gpu 0 --case $(MyArg1) -s 0.001

error = /home/yxiu/Code/NeuralUDF/logs/train_wmask_$(MyArg1).err
output = /home/yxiu/Code/NeuralUDF/logs/train_wmask_$(MyArg1).out
log = /home/yxiu/Code/NeuralUDF/logs/train_wmask_$(MyArg1).log

request_memory = 50000
request_disk = 5G
request_cpus = 8
request_gpus = 1
requirements = (CUDADeviceName=="Quadro RTX 6000" && UtsnameNodename=!="g093" && UtsnameNodename=!="g081")

queue MyArg1 from /home/yxiu/Code/NeuralUDF/hat_lst.txt
