executable = /home/yxiu/Code/NeuralUDF/bashs/bash_garment_blending_ft.sh
arguments = --gpu 0 --case $(MyArg1) -s 0.01

error = /home/yxiu/Code/NeuralUDF/logs/train_$(MyArg1)_ft.err
output = /home/yxiu/Code/NeuralUDF/logs/train_$(MyArg1)_ft.out
log = /home/yxiu/Code/NeuralUDF/logs/train_$(MyArg1)_ft.log

request_memory = 10000
request_disk = 5G
request_cpus = 6
request_gpus = 1
requirements = TARGET.CUDACapability > 7.5
requirements = TARGET.CUDAGlobalMemoryMb > 10000

queue MyArg1 from /home/yxiu/Code/NeuralUDF/train_lst.txt
